# Site settings
title: "Cora Sula"
description: "Cora's personal website."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Cora Sula"
resume_title:                   "Graduate Research Assistant"

# used for the contact button in _layouts/resume.html
# resume_contact_email:           "csula@gmu.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
resume_contact_address:         "Washington, D.C."
resume_contact_address:         "csula (at) gmu (dot) edu"
# resume_contact_telephone:       "csula (at) gmu (dot) edu"

resume_header_contact_info:     "Washington, D.C."
resume_contact_telephone:       "csula (at) gmu (dot) edu"
display_header_telephone:       "true"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a second-year graduate student in Information Technology, focusing on Human-Computer Interaction. I received my Bachelor of Science in Computer Science. My research interests are HCI, HRI, and AI. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank 
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/csula13"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/cora-sula-3b478619b"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://csula13.github.io/"
  # resume_medium_url:            "https://csula13.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
